### ISSUE TITLE
Broken by Rails 6.1?

### ISSUE THREAD

**Issue by brettmarl** [rails/actionpack-action_caching#76]
Upgraded to Ruby 2.7.2 and Rails 6.1 and I get the following error running under Rails 6.1. Works fine with Rails 6.0.3.4

`
NoMethodError: undefined method `eager_autoload' for ActionController::Caching:Module
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-action_caching-1.2.1/lib/action_controller/action_caching.rb:5:in `<module:Caching>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-action_caching-1.2.1/lib/action_controller/action_caching.rb:4:in `<module:ActionController>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-action_caching-1.2.1/lib/action_controller/action_caching.rb:3:in `<top (required)>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-action_caching-1.2.1/lib/actionpack/action_caching/railtie.rb:8:in `block (2 levels) in <class:Railtie>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-6.1.0/lib/action_controller/api.rb:148:in `<class:API>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-6.1.0/lib/action_controller/api.rb:89:in `<module:ActionController>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-6.1.0/lib/action_controller/api.rb:7:in `<top (required)>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/jbuilder-2.10.1/lib/jbuilder/railtie.rb:20:in `block (2 levels) in <class:Railtie>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-6.1.0/lib/action_controller/base.rb:271:in `<class:Base>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-6.1.0/lib/action_controller/base.rb:166:in `<module:ActionController>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actionpack-6.1.0/lib/action_controller/base.rb:7:in `<top (required)>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
/home/dev/.rvm/gems/ruby-2.7.2/gems/railties-6.1.0/lib/rails/engine.rb:506:in `helpers'
/home/dev/.rvm/gems/ruby-2.7.2/gems/railties-6.1.0/lib/rails/railtie.rb:207:in `public_send'
/home/dev/.rvm/gems/ruby-2.7.2/gems/railties-6.1.0/lib/rails/railtie.rb:207:in `method_missing'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actiontext-6.1.0/lib/action_text/engine.rb:42:in `block (3 levels) in <class:Engine>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:42:in `each'
/home/dev/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actiontext-6.1.0/lib/action_text/engine.rb:41:in `block (2 levels) in <class:Engine>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actiontext-6.1.0/lib/action_text/engine.rb:40:in `each'
/home/dev/.rvm/gems/ruby-2.7.2/gems/actiontext-6.1.0/lib/action_text/engine.rb:40:in `block in <class:Engine>'
/home/dev/.rvm/gems/ruby-2.7.2/gems/railties-6.1.0/lib/rails/initializable.rb:32:in `instance_exec'
/home/dev/.rvm/gems/ruby-2.7.2/gems/railties-6.1.0/lib/rails/initializable.rb:32:in `run'
/home/dev/.rvm/gems/ruby-2.7.2/gems/railties-6.1.0/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/dev/.rvm/gems/ruby-2.7.2/gems/railties-6.1.0/lib/rails/initializable.rb:60:in `run_initializers'
/home/dev/.rvm/gems/ruby-2.7.2/gems/railties-6.1.0/lib/rails/application.rb:384:in `initialize!'
`

**Comment by brettmarl** [comment]
I'm not that familiar with Rails internals - but a quick poke around suggests this might be the impacting change:

https://github.com/rails/rails/commit/da21ac7bf9d8d2de4e9dbf4c137ad3e8ea50a495#diff-437dd235c4623a5c8ed3a1a6aedea0806e7d055bbea6c6130f3c3e8c2ab7f69e

**Comment by jathayde** [comment]
I'm seeing this as well running on the master branch of this gem.

**Comment by jathayde** [comment]
Fixed for me in Pull Request #77

**Comment by jpgeek** [comment]
Works for m on master (7bdfa663274a2620dde8daad7dcb995c1cfef840).  Is there going to be a new gem released soon?

**Comment by sikachu** [comment]
@rafaelfranca should we do another release for Rails 6.1 support?

**Comment by Thornolf** [comment]
@rafaelfranca @sikachu Hello, is it possible to release it to RubyGems please ? That would be awesome we really need it for Rails 6.1 ♥️

**Comment by smok-gpsw** [comment]
@rafaelfranca @sikachu can you release this Gems with 6.1 support please?

**Comment by exocode** [comment]
Hi there, 

did I miss something? 

I tried this (most recent commit)
`gem 'actionpack-action_caching', github: 'rails/actionpack-action_caching', :branch => '7bdfa663274a2620dde8daad7dcb995c1cfef840'`
and this
`gem 'actionpack-action_caching', github: 'rails/actionpack-action_caching', :branch => 'master'`

But I still get

`#<NoMethodError: undefined method 'caches_action' for CategoryController:Class>"`

>> Rails.version
=> "6.1.3.1"
>> ruby '2.7.2'

**Comment by jathayde** [comment]
@exocode Hmm. You should be fine with that. I don't even define the branch, just the GitHub, and it's been working for me. Have you tried `bundle update actionpack-action_caching` or nuking the Gemfile.lock and running bundle again? Seems like something isn't reading that in. Might also try `require actionpack/action_caching` at the top of that file to see if you can push it down to the controller level (although I don't need that in my 6.1.3.1/2.7.2 app).

**Comment by exocode** [comment]
Hi @jathayde,

I tried now the following: 
- `bundle update actionpack-action_caching`
- deleted `Gemfile.lock` && `bundle install`
- deleted /tmp files
- `rails dev:cache` which generates the `caching-dev.txt`

### What else can I do?
Thank you in advance!

This is my development.rb

```ruby
  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join('tmp', 'caching-dev.txt').exist?
    config.cache_store = :memory_store
    config.public_file_server.headers = {
      'Cache-Control' => "public, max-age=#{2.days.to_i}"
    }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end
```


category_controller.rb
```ruby
require "actionpack/action_caching"
class CategoryController < ApplicationController

  skip_before_action :authorize_request #, only: [:index]
  caches_action :index

  def index
    root_categories = Category.all
    # hash = CategoryRootSerializer.new(root_categories).serializable_hash
    hash = root_categories.map { |root| root.mapping }
    json_response(hash)
  end
end
```

Gemfile
```
gem 'rails', '~> 6.1.3'
gem 'actionpack-action_caching', github: 'ExpectedValue/actionpack-action_caching'
gem 'bootsnap', '>= 1.4.4', require: false
```
complete `Gemfile.lock`
https://pastebin.com/bNSX5wBS

and this is the complete stacktrace:
https://pastebin.com/gQnbtPFm

```
/usr/local/bin/zsh -c "bash -c 'env RBENV_VERSION=2.7.2 /usr/local/Cellar/rbenv/1.1.2/libexec/rbenv exec ruby /Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-2.3.1/bin/rdebug-ide --key-value --step-over-in-blocks --disable-int-handler --evaluation-timeout 10 --evaluation-control --time-limit 100 --memory-limit 0 --rubymine-protocol-extensions --port 49943 --host 0.0.0.0 --dispatcher-port 49944 -- /Users/jan/Coding/RubymineProjects/metashop-v1/bin/rails server -b 0.0.0.0 -p 3000 -e development'"
Fast Debugger (ruby-debug-ide 2.3.1, debase 2.3.2, file filtering is supported, block breakpoints supported, smart steps supported, obtaining return values supported, partial obtaining of instance variables supported) listens on 0.0.0.0:49943
=> Booting Puma
=> Rails 6.1.3.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
Elasticsearch Version: {"number"=>"7.12.0", "build_flavor"=>"default", "build_type"=>"tar", "build_hash"=>"78722783c38caa25a70982b5b042074cde5d3b3a", "build_date"=>"2021-03-18T06:17:15.410153305Z", "build_snapshot"=>false, "lucene_version"=>"8.8.0", "minimum_wire_compatibility_version"=>"6.8.0", "minimum_index_compatibility_version"=>"6.0.0-beta1"}
Puma starting in single mode...
* Version 3.12.6 (ruby 2.7.2-p137), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
2021-04-03 21:27:30 +0200: Rack app error handling request { GET /category/index }
#<NoMethodError: undefined method `eager_autoload' for ActionController::Caching:Module>
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-action_caching-1.2.1/lib/action_controller/action_caching.rb:5:in `<module:Caching>'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-action_caching-1.2.1/lib/action_controller/action_caching.rb:4:in `<module:ActionController>'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-action_caching-1.2.1/lib/action_controller/action_caching.rb:3:in `<main>'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-action_caching-1.2.1/lib/actionpack/action_caching/railtie.rb:8:in `block (2 levels) in <class:Railtie>'
/Users/jan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
```

**Comment by exocode** [comment]
Ok I think I found it here: 
https://github.com/rails/actionpack-action_caching/issues/12#issuecomment-281166960

> ...case you application controller inherited from `ActionController::API` , just added in `ApplicationController`

`  include ActionController::Caching`

**Comment by exocode** [comment]
But I am still hanging: 
The problem seems to be: 
`ActionController::API` which wont work I have to use
`ActionController::Base` which is not my favour. Is there any workaround?

**Comment by jathayde** [comment]
The only difference I have is that I'm running redis locally for cache storage and not running ElasticSearch. My development.rb is a bit more explicit:

```
  if Rails.root.join('tmp', 'caching-dev.txt').exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :redis_cache_store, { url: "redis://127.0.0.1:6379/1/cache" }
    config.public_file_server.headers = {
      'Cache-Control' => "public, max-age=#{2.days.to_i}"
    }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end
```

You might try adding `config.action_controller.perform_caching = true` and seeing if that does anything. 

Have you tried this without your changes in your local branch (ExpectedValue fork)?

Only other thing I've found is this SO, which may relate to some Zeitwork loading issues: 
https://stackoverflow.com/questions/60649082/nomethoderror-undefined-method-eager-load-paths-for-i18nconfig0x00007fce

**Comment by pikitgb** [comment]
I'm getting: anyone know how to bypass this ?

```
2021-04-28 20:44:50 -0400 Rack app ("GET /action_name" - (::1)): #<NoMethodError: undefined method `eager_autoload' for ActionController::Caching:Module>
/Users/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.3.1/lib/action_controller/base.rb:205: warning: already initialized constant ActionController::Base::MODULES
```

**Comment by puneetpandey** [comment]
replacing `gem 'actionpack-action_caching'` with `gem 'actionpack-action_caching', github: 'rails/actionpack-action_caching', branch: 'master'` in Gemfile worked for me. Not sure what's the issue in releasing to Rubygems!

**Comment by attenzione** [comment]
> @rafaelfranca @sikachu @matthewd can you release this Gems with 6.1 support please?

@amatsuda maybe you can help us?

**Comment by pixeltrix** [comment]
@attenzione if no-one gets to it before then I'll do it at the weekend

**Comment by pixeltrix** [comment]
Sorry for being a little late - had to fix some servers over the weekend 😩 

Have pushed a new version now: https://rubygems.org/gems/actionpack-action_caching/versions/1.2.2
